permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: RuifLI
  email: ruifli@outlook.com
  link: http://ruifli.com
  weibo: http://weibo.com/ruifli
  github: http://github.com/RuifLI

# 站点信息
title: RuifLI's博客 
description: RuifLI's博客 
url: http://ruifli.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://ww2.sinaimg.cn/mw690/6e456299jw8ewsw1yjqkqj20hs0hu755.jpg
favicon: https://assets-cdn.github.com/favicon.ico
# google analytics 设置
ga:
  id: UA-54767140-1
  url: ruifli.com

# disqus 设置
disqus:
  shortname: ruifli
